### ISSUE TITLE
iPCL crashing apps during startup

### ISSUE THREAD

**Issue by tgrf** [Roche/iPCLPublic#6]
In current version of iPCL, when the user was previously logged in into the application and he changed his password, during next application launch iPCL calls performAppMainLogic method in appDelegate simultaneously with displaying a login view, what ends up with an app crash/freeze.

Logs:
<Warning>: ERROR:invalid login credential
<Warning>: ERROR:login failed, invalid credentials invalid login credential
<Warning>: Warning: Attempt to present <iPCLNavigationController: 0x1569b990> on <LaunchViewController: 0x1566c750> while a presentation is in progress!

**Comment by indykl** [comment]
Closing due to no contact from the requester.
